/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IDiscourseTopic } from "./utils/discourse";
export namespace Components {
    interface DiscourseEmbedTopics {
        "categoryId"?: number;
        "forumBaseUrl": string;
        "newWindow"?: boolean;
        "numTopics": number;
        "offset": number;
        "tag"?: string;
    }
    interface DiscourseTopicLink {
        "newWindow"?: boolean;
        "noopener"?: boolean;
        "noreferrer"?: boolean;
        "topic": IDiscourseTopic;
    }
}
declare global {
    interface HTMLDiscourseEmbedTopicsElement extends Components.DiscourseEmbedTopics, HTMLStencilElement {
    }
    var HTMLDiscourseEmbedTopicsElement: {
        prototype: HTMLDiscourseEmbedTopicsElement;
        new (): HTMLDiscourseEmbedTopicsElement;
    };
    interface HTMLDiscourseTopicLinkElement extends Components.DiscourseTopicLink, HTMLStencilElement {
    }
    var HTMLDiscourseTopicLinkElement: {
        prototype: HTMLDiscourseTopicLinkElement;
        new (): HTMLDiscourseTopicLinkElement;
    };
    interface HTMLElementTagNameMap {
        "discourse-embed-topics": HTMLDiscourseEmbedTopicsElement;
        "discourse-topic-link": HTMLDiscourseTopicLinkElement;
    }
}
declare namespace LocalJSX {
    interface DiscourseEmbedTopics {
        "categoryId"?: number;
        "forumBaseUrl"?: string;
        "newWindow"?: boolean;
        "numTopics"?: number;
        "offset"?: number;
        "tag"?: string;
    }
    interface DiscourseTopicLink {
        "newWindow"?: boolean;
        "noopener"?: boolean;
        "noreferrer"?: boolean;
        "topic"?: IDiscourseTopic;
    }
    interface IntrinsicElements {
        "discourse-embed-topics": DiscourseEmbedTopics;
        "discourse-topic-link": DiscourseTopicLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "discourse-embed-topics": LocalJSX.DiscourseEmbedTopics & JSXBase.HTMLAttributes<HTMLDiscourseEmbedTopicsElement>;
            "discourse-topic-link": LocalJSX.DiscourseTopicLink & JSXBase.HTMLAttributes<HTMLDiscourseTopicLinkElement>;
        }
    }
}
